# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soyventana.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(900, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 730))
        MainWindow.setMaximumSize(QtCore.QSize(900, 730))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/soyicono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabSoy = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSoy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSoy.sizePolicy().hasHeightForWidth())
        self.tabSoy.setSizePolicy(sizePolicy)
        self.tabSoy.setMaximumSize(QtCore.QSize(16777215, 775))
        self.tabSoy.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabSoy.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSoy.setElideMode(QtCore.Qt.ElideNone)
        self.tabSoy.setDocumentMode(False)
        self.tabSoy.setTabsClosable(False)
        self.tabSoy.setObjectName("tabSoy")
        self.tabCaro = QtWidgets.QWidget()
        self.tabCaro.setObjectName("tabCaro")
        self.groupBox_dados = QtWidgets.QGroupBox(self.tabCaro)
        self.groupBox_dados.setGeometry(QtCore.QRect(10, 10, 531, 181))
        self.groupBox_dados.setObjectName("groupBox_dados")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_dados)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.compas_01 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_01.setMinimum(1)
        self.compas_01.setMaximum(6)
        self.compas_01.setProperty("value", 3)
        self.compas_01.setObjectName("compas_01")
        self.gridLayout_2.addWidget(self.compas_01, 0, 0, 1, 1)
        self.compas_02 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_02.setMinimum(1)
        self.compas_02.setMaximum(6)
        self.compas_02.setProperty("value", 3)
        self.compas_02.setObjectName("compas_02")
        self.gridLayout_2.addWidget(self.compas_02, 0, 1, 1, 1)
        self.compas_03 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_03.setMinimum(1)
        self.compas_03.setMaximum(6)
        self.compas_03.setProperty("value", 3)
        self.compas_03.setObjectName("compas_03")
        self.gridLayout_2.addWidget(self.compas_03, 0, 2, 1, 1)
        self.compas_04 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_04.setMinimum(1)
        self.compas_04.setMaximum(6)
        self.compas_04.setProperty("value", 3)
        self.compas_04.setObjectName("compas_04")
        self.gridLayout_2.addWidget(self.compas_04, 0, 3, 1, 1)
        self.compas_05 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_05.setMinimum(1)
        self.compas_05.setMaximum(6)
        self.compas_05.setProperty("value", 3)
        self.compas_05.setObjectName("compas_05")
        self.gridLayout_2.addWidget(self.compas_05, 1, 0, 1, 1)
        self.compas_06 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_06.setMinimum(1)
        self.compas_06.setMaximum(6)
        self.compas_06.setProperty("value", 3)
        self.compas_06.setObjectName("compas_06")
        self.gridLayout_2.addWidget(self.compas_06, 1, 1, 1, 1)
        self.compas_07 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_07.setMinimum(1)
        self.compas_07.setMaximum(6)
        self.compas_07.setProperty("value", 3)
        self.compas_07.setObjectName("compas_07")
        self.gridLayout_2.addWidget(self.compas_07, 1, 2, 1, 1)
        self.compas_08 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_08.setMinimum(1)
        self.compas_08.setMaximum(6)
        self.compas_08.setProperty("value", 3)
        self.compas_08.setObjectName("compas_08")
        self.gridLayout_2.addWidget(self.compas_08, 1, 3, 1, 1)
        self.compas_09 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_09.setMinimum(1)
        self.compas_09.setMaximum(6)
        self.compas_09.setProperty("value", 3)
        self.compas_09.setObjectName("compas_09")
        self.gridLayout_2.addWidget(self.compas_09, 2, 0, 1, 1)
        self.compas_10 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_10.setMinimum(1)
        self.compas_10.setMaximum(6)
        self.compas_10.setProperty("value", 3)
        self.compas_10.setObjectName("compas_10")
        self.gridLayout_2.addWidget(self.compas_10, 2, 1, 1, 1)
        self.compas_11 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_11.setMinimum(1)
        self.compas_11.setMaximum(6)
        self.compas_11.setProperty("value", 3)
        self.compas_11.setObjectName("compas_11")
        self.gridLayout_2.addWidget(self.compas_11, 2, 2, 1, 1)
        self.compas_12 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_12.setMinimum(1)
        self.compas_12.setMaximum(6)
        self.compas_12.setProperty("value", 3)
        self.compas_12.setObjectName("compas_12")
        self.gridLayout_2.addWidget(self.compas_12, 2, 3, 1, 1)
        self.compas_13 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_13.setMinimum(1)
        self.compas_13.setMaximum(6)
        self.compas_13.setProperty("value", 3)
        self.compas_13.setObjectName("compas_13")
        self.gridLayout_2.addWidget(self.compas_13, 3, 0, 1, 1)
        self.compas_14 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_14.setMinimum(1)
        self.compas_14.setMaximum(6)
        self.compas_14.setProperty("value", 3)
        self.compas_14.setObjectName("compas_14")
        self.gridLayout_2.addWidget(self.compas_14, 3, 1, 1, 1)
        self.compas_15 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_15.setMinimum(1)
        self.compas_15.setMaximum(6)
        self.compas_15.setProperty("value", 3)
        self.compas_15.setObjectName("compas_15")
        self.gridLayout_2.addWidget(self.compas_15, 3, 2, 1, 1)
        self.compas_16 = QtWidgets.QSpinBox(self.groupBox_dados)
        self.compas_16.setMinimum(1)
        self.compas_16.setMaximum(6)
        self.compas_16.setProperty("value", 3)
        self.compas_16.setObjectName("compas_16")
        self.gridLayout_2.addWidget(self.compas_16, 3, 3, 1, 1)
        self.botonDados = QtWidgets.QPushButton(self.groupBox_dados)
        self.botonDados.setObjectName("botonDados")
        self.gridLayout_2.addWidget(self.botonDados, 0, 4, 1, 1)
        self.botonComponer = QtWidgets.QPushButton(self.groupBox_dados)
        self.botonComponer.setEnabled(False)
        self.botonComponer.setObjectName("botonComponer")
        self.gridLayout_2.addWidget(self.botonComponer, 1, 4, 1, 1)
        self.botonStop = QtWidgets.QPushButton(self.groupBox_dados)
        self.botonStop.setEnabled(False)
        self.botonStop.setObjectName("botonStop")
        self.gridLayout_2.addWidget(self.botonStop, 2, 4, 1, 1)
        self.botonPlay = QtWidgets.QPushButton(self.groupBox_dados)
        self.botonPlay.setEnabled(False)
        self.botonPlay.setObjectName("botonPlay")
        self.gridLayout_2.addWidget(self.botonPlay, 3, 4, 1, 1)
        self.groupBox_partitura = QtWidgets.QGroupBox(self.tabCaro)
        self.groupBox_partitura.setGeometry(QtCore.QRect(10, 200, 861, 451))
        self.groupBox_partitura.setObjectName("groupBox_partitura")
        self.botonPDF = QtWidgets.QPushButton(self.groupBox_partitura)
        self.botonPDF.setEnabled(False)
        self.botonPDF.setGeometry(QtCore.QRect(10, 40, 150, 29))
        self.botonPDF.setObjectName("botonPDF")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_partitura)
        self.groupBox.setGeometry(QtCore.QRect(240, 80, 611, 331))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(410, 40, 191, 284))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 191, 284))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(210, 40, 191, 284))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_partitura)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 221, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 201, 284))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_comunicacion = QtWidgets.QGroupBox(self.tabCaro)
        self.groupBox_comunicacion.setGeometry(QtCore.QRect(550, 10, 321, 181))
        self.groupBox_comunicacion.setObjectName("groupBox_comunicacion")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_comunicacion)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.salidaTexto = QtWidgets.QPlainTextEdit(self.groupBox_comunicacion)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        self.salidaTexto.setFont(font)
        self.salidaTexto.setReadOnly(True)
        self.salidaTexto.setObjectName("salidaTexto")
        self.gridLayout_5.addWidget(self.salidaTexto, 0, 0, 1, 1)
        self.tabSoy.addTab(self.tabCaro, "")
        self.gridLayout.addWidget(self.tabSoy, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 30))
        self.menubar.setObjectName("menubar")
        self.menuSoy_Legion = QtWidgets.QMenu(self.menubar)
        self.menuSoy_Legion.setObjectName("menuSoy_Legion")
        self.menuA_yuda = QtWidgets.QMenu(self.menubar)
        self.menuA_yuda.setObjectName("menuA_yuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Salir = QtWidgets.QAction(MainWindow)
        self.action_Salir.setObjectName("action_Salir")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("soyicono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon1)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.action_Ver_reglas_del_juego = QtWidgets.QAction(MainWindow)
        self.action_Ver_reglas_del_juego.setObjectName("action_Ver_reglas_del_juego")
        self.actionVer_Plantilla = QtWidgets.QAction(MainWindow)
        self.actionVer_Plantilla.setObjectName("actionVer_Plantilla")
        self.menuSoy_Legion.addAction(self.actionVer_Plantilla)
        self.menuSoy_Legion.addSeparator()
        self.menuSoy_Legion.addAction(self.action_Salir)
        self.menuA_yuda.addAction(self.action_Ver_reglas_del_juego)
        self.menuA_yuda.addSeparator()
        self.menuA_yuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuSoy_Legion.menuAction())
        self.menubar.addAction(self.menuA_yuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabSoy.setCurrentIndex(0)
        self.action_Salir.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.compas_01, self.compas_02)
        MainWindow.setTabOrder(self.compas_02, self.compas_03)
        MainWindow.setTabOrder(self.compas_03, self.compas_04)
        MainWindow.setTabOrder(self.compas_04, self.compas_05)
        MainWindow.setTabOrder(self.compas_05, self.compas_06)
        MainWindow.setTabOrder(self.compas_06, self.compas_07)
        MainWindow.setTabOrder(self.compas_07, self.compas_08)
        MainWindow.setTabOrder(self.compas_08, self.compas_09)
        MainWindow.setTabOrder(self.compas_09, self.compas_10)
        MainWindow.setTabOrder(self.compas_10, self.compas_11)
        MainWindow.setTabOrder(self.compas_11, self.compas_12)
        MainWindow.setTabOrder(self.compas_12, self.compas_13)
        MainWindow.setTabOrder(self.compas_13, self.compas_14)
        MainWindow.setTabOrder(self.compas_14, self.compas_15)
        MainWindow.setTabOrder(self.compas_15, self.compas_16)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soy Legión Ana Carolina"))
        self.groupBox_dados.setTitle(_translate("MainWindow", "Generador de piezas"))
        self.botonDados.setText(_translate("MainWindow", "&Lanza dados"))
        self.botonComponer.setText(_translate("MainWindow", "&Compone"))
        self.botonStop.setText(_translate("MainWindow", "&Detiene"))
        self.botonPlay.setText(_translate("MainWindow", "&Toca"))
        self.groupBox_partitura.setTitle(_translate("MainWindow", "Pieza generada"))
        self.botonPDF.setText(_translate("MainWindow", "&Visor externo..."))
        self.groupBox.setTitle(_translate("MainWindow", "Particellas"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Partitura"))
        self.groupBox_comunicacion.setTitle(_translate("MainWindow", "Comunicación"))
        self.salidaTexto.setPlainText(_translate("MainWindow", "¿Cómo sabrá ser, no?", "Hola Mundo!"))
        self.tabSoy.setTabText(self.tabSoy.indexOf(self.tabCaro), _translate("MainWindow", "Ana &Carolina"))
        self.menuSoy_Legion.setTitle(_translate("MainWindow", "Soy &Legión"))
        self.menuA_yuda.setTitle(_translate("MainWindow", "A&yuda"))
        self.action_Salir.setText(_translate("MainWindow", "&Salir"))
        self.action_Salir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAcerca_de.setText(_translate("MainWindow", "A&cerca de..."))
        self.action_Ver_reglas_del_juego.setText(_translate("MainWindow", "&Ver reglas del juego..."))
        self.actionVer_Plantilla.setText(_translate("MainWindow", "Ver &Plantilla..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

